// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mahalanobis_cpp
NumericVector mahalanobis_cpp(NumericMatrix X, NumericVector mu, NumericMatrix Sinv);
RcppExport SEXP _MOutliers_mahalanobis_cpp(SEXP XSEXP, SEXP muSEXP, SEXP SinvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Sinv(SinvSEXP);
    rcpp_result_gen = Rcpp::wrap(mahalanobis_cpp(X, mu, Sinv));
    return rcpp_result_gen;
END_RCPP
}
// pca_distances_cpp
NumericVector pca_distances_cpp(NumericMatrix scores, NumericVector center);
RcppExport SEXP _MOutliers_pca_distances_cpp(SEXP scoresSEXP, SEXP centerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type center(centerSEXP);
    rcpp_result_gen = Rcpp::wrap(pca_distances_cpp(scores, center));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MOutliers_mahalanobis_cpp", (DL_FUNC) &_MOutliers_mahalanobis_cpp, 3},
    {"_MOutliers_pca_distances_cpp", (DL_FUNC) &_MOutliers_pca_distances_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_MOutliers(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
