# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mahalanobis_cpp <- function(X, mu, Sinv) {
    .Call(`_MOutliers_mahalanobis_cpp`, X, mu, Sinv)
}

pca_distances_cpp <- function(scores, center) {
    .Call(`_MOutliers_pca_distances_cpp`, scores, center)
}

